ingresses:
  - name: ""
    namespace: ""
    whitelist:
      enabled: false
      whitelistSourceRange: ""
    domain:
      name: ""
      targetService: ""

issuers:
  - name: letsencrypt-nginx
    namespace: ""
    email: ""