ingress:
  name: ""
  namespace: ""
  whitelist:
    enabled: false
    whitelistSourceRange: ""
  domain:
    name: ""
    targetService: ""

issuer:
  name: ""
  namespace: ""
  email: ""

ingress-nginx:
  controller:
    ingressClassResource:
      name: ""
