ingresses:
  - name: plant-coach
    namespace: plant-coach-production
    whitelist:
      enabled: false
      whitelistSourceRange: ""
    domain:
      name: "plantcoach.app"
      targetService: plant-coach-fe

issuers:
  - name: letsencrypt-nginx
    namespace: plant-coach-production
    email: ""