{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}-ingress-nginx
    app.kubernetes.io/part-of: nginx-ingress-maintainer
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
    {{- if .whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .whitelistSourceRange }}
    {{- end }}
spec:
  # Ingress resources need to have the ingressClassName field set to 
  # the value of the class of the Ingress Controller the user wants to use.
  ingressClassName: {{ .namespace }}-nginx
  tls:
   - hosts:
     - {{ .domain.name }}
     secretName: letsencrypt-nginx-{{ .name }}-app
  rules:
  - host: {{ .domain.name }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .domain.targetService }}
            port:
              number: 80

{{- end }}
