{{- range .Values.issuers }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  acme:
    email: {{ .email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .name }}-private-key
    solvers:
      - http01:
          ingress:
            class: {{ .namespace }}-nginx
{{- end }}