---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.issuer.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "{{ .Values.issuer.name }}-{{ .Values.ingress.name }}-nginx-private-key"
    solvers:
    - dns01:
        # ingress:
        #   class: {{ .Values.ingress.name }}-nginx
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token